name: Build 3DSX

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install devkitARM + libctru
        run: |
          sudo apt-get update
          sudo apt-get install -y git build-essential libarchive-dev
          wget https://apt.devkitpro.org/install-devkitpro-pacman -O install-pacman
          chmod +x install-pacman
          sudo ./install-pacman

          echo "PATH=/opt/devkitpro/devkitARM/bin:$PATH" >> $GITHUB_ENV
          echo "DEVKITPRO=/opt/devkitpro" >> $GITHUB_ENV
          echo "DEVKITARM=/opt/devkitpro/devkitARM" >> $GITHUB_ENV

          sudo dkp-pacman -Sy --noconfirm
          sudo dkp-pacman -S --noconfirm devkitARM libctru

      - name: Build .3dsx
        run: make

      - name: Upload .3dsx
        uses: actions/upload-artifact@v4
        with:
          name: nosleep.3dsx
          path: nosleep.3dsx
