name: Build 3DSX

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: devkitpro/devkitarm

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up environment
        run: |
          echo "DEVKITPRO=/opt/devkitpro" >> $GITHUB_ENV
          echo "DEVKITARM=/opt/devkitpro/devkitARM" >> $GITHUB_ENV

      - name: Install libctru
        run: |
          dkp-pacman -Sy --noconfirm libctru

      - name: Build .3dsx
        run: make

      - name: Upload .3dsx
        uses: actions/upload-artifact@v4
        with:
          name: nosleep.3dsx
          path: nosleep.3dsx
